In [7]:
import numpy as np

Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [45]:
vector = np.arange(1, 11, dtype=int)
print(vector)


[ 1  2  3  4  5  6  7  8  9 10]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [41]:
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]



Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.



In [35]:
random_array = np.random.randint(1, 11, size=(3, 3))
print(random_array)

[[2 8 3]
 [8 1 9]
 [6 1 5]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [57]:
random_array = np.random.uniform(1, 10, size=(3, 3))
print(random_array)

[[8.25336454 4.47423606 6.23693326]
 [2.76639188 6.74079301 2.19226757]
 [9.82315879 4.70041042 2.65061821]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [55]:
# Arrays
ar1 = np.random.randint(1, 11, size=5)
print("ar1:", ar1)
ar2 = np.random.randint(1, 11, size=5)
print("ar2:", ar2)

# Element-wise Sum
sum_array = ar1 + ar2
print("Sum:", sum_array)

# Element-wise Difference
difference_array = ar1 - ar2
print("Difference:", difference_array)

# Element-wise Multiplication
product_array = ar1 * ar2
print("Product:", product_array)

ar1: [ 2  2  2 10  6]
ar2: [9 8 6 3 8]
Sum: [11 10  8 13 14]
Difference: [-7 -6 -4  7 -2]
Product: [18 16 12 30 48]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [59]:
# Arrays
ar1 = np.random.uniform(1, 11, size=7)
print("ar1:", ar1)
ar2 = np.random.uniform(1, 11, size=7)
print("ar2:", ar2)

# Dot Product
dot_product = np.dot(ar1, ar2)
print("Dot Product:", dot_product)

ar1: [1.15832226 4.60471515 8.22091784 6.98186338 8.57309545 9.47857411
 8.15001616]
ar2: [ 3.14312413 10.74301677  2.47553051  9.01618863  8.57941387  6.28127057
 10.41319869]
Dot Product: 354.3675731264317


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [69]:
# Create a 2x2 matrix
matrix_a = np.random.randint(1, 11, size=(2, 2))
print("Matrix A (2x2):\n", matrix_a)

# Create a 2x3 matrix
matrix_b = np.random.randint(1, 11, size=(2, 3))
print("Matrix B (2x3):\n", matrix_b)

# Matrix multiplication
product_matrix = matrix_a @ matrix_b 
# np.matmul(matrix_a, matrix_b) is the same thing as @, np.dot(matrix_a, matrix_b) acts counterintuitive on tensors

print("Product (Matrix A * Matrix B):\n", product_matrix)

Matrix A (2x2):
 [[4 3]
 [6 2]]
Matrix B (2x3):
 [[6 3 1]
 [1 3 5]]
Product (Matrix A * Matrix B):
 [[27 21 19]
 [38 24 16]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [65]:
# Generate a random 3x3 matrix
matrix = np.random.randint(1, 11, size=(3, 3))

# Compute the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

# Check
check = matrix @ inverse_matrix

# Output the matrix and its inverse
print("Matrix:\n", matrix)
print("Inverse of the Matrix:\n", inverse_matrix)
print("Check: matrix @ inverse_matrix \n", check) # almost lol, but it's python, up to 10^(-15)

Matrix:
 [[ 5 10  5]
 [ 4  7  6]
 [10  2 10]]
Inverse of the Matrix:
 [[ 0.32222222 -0.5         0.13888889]
 [ 0.11111111  0.         -0.05555556]
 [-0.34444444  0.5        -0.02777778]]
Check: matrix @ inverse_matrix 
 [[1.00000000e+00 0.00000000e+00 1.66533454e-16]
 [2.22044605e-16 1.00000000e+00 8.32667268e-17]
 [2.22044605e-16 0.00000000e+00 1.00000000e+00]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [73]:
# Generate a random 4x4 matrix with values in the range [0, 1)
matrix = np.random.rand(4, 4)

# Compute the transpose of the matrix
transposed_matrix = matrix.T

# Output the matrix and its transpose
print("Matrix:\n", matrix)
print("Transposed Matrix:\n", transposed_matrix)

Matrix:
 [[0.67366875 0.38544835 0.97712629 0.30129761]
 [0.0554489  0.39600222 0.58198972 0.01242378]
 [0.85792259 0.65273712 0.57724078 0.03390983]
 [0.44250054 0.2940478  0.43813021 0.41902904]]
Transposed Matrix:
 [[0.67366875 0.0554489  0.85792259 0.44250054]
 [0.38544835 0.39600222 0.65273712 0.2940478 ]
 [0.97712629 0.58198972 0.57724078 0.43813021]
 [0.30129761 0.01242378 0.03390983 0.41902904]]



Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.


In [75]:
# Generate a random 3x4 matrix
matrix = np.random.randint(1, 11, size=(3, 4))

# Generate a random vector
vector = np.random.randint(1, 11, size=4)

# Multiplication matrix @ vector
result = matrix @ vector

# Output
print("Matrix:\n", matrix)
print("Vector:\n", vector)
print("Result:\n", result)

Matrix:
 [[ 1  1  3  8]
 [ 2  7  3 10]
 [ 5  4  6  7]]
Vector:
 [3 2 8 1]
Result:
 [37 54 78]



Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.



In [77]:
# Generate a random 2x3 matrix with values in the range [0, 1)
matrix = np.random.rand(2, 3)

# Generate a random vector
vector = np.random.rand(3)

# Multiplication matrix @ vector
result = matrix @ vector

# Output
print("Matrix:\n", matrix)
print("Vector:\n", vector)
print("Result:\n", result)

Matrix:
 [[0.073357   0.80013362 0.3159215 ]
 [0.96861702 0.66600707 0.57836104]]
Vector:
 [0.5110327  0.15432105 0.05518974]
Result:
 [0.17840091 0.62969347]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.


In [79]:
# Generate random 2x2 matriсes
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Multiplication matrix * matrix
result = matrix1 * matrix2

# Output
print("Matrix1:\n", matrix1)
print("Matrix2:\n", matrix2)
print("Result:\n", result)

Matrix1:
 [[1 7]
 [2 9]]
Matrix2:
 [[ 1  4]
 [10  8]]
Result:
 [[ 1 28]
 [20 72]]



Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.



In [81]:
# Generate random 2x2 matriсes
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Multiplication matrix @ matrix
result = matrix1 @ matrix2

# Output
print("Matrix1:\n", matrix1)
print("Matrix2:\n", matrix2)
print("Result:\n", result)

Matrix1:
 [[ 5 10]
 [ 2  8]]
Matrix2:
 [[ 3  8]
 [10  4]]
Result:
 [[115  80]
 [ 86  48]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.


In [85]:
# Generate a random 5x5 matrix with values in the range [1, 100]
matrix = np.random.randint(1, 101, size=(5, 5))

# Compute the sum of all the elements in the matrix
sum_of_elements = np.sum(matrix)

# Output
print("Matrix:\n", matrix)
print("Sum:\n", sum_of_elements)

Matrix:
 [[ 88  88  36  45  55]
 [ 29 100  75  60  27]
 [ 24  70  44  50  77]
 [ 81  30  21  81  68]
 [ 14   8  61  11 100]]
Sum:
 1343



Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.


In [87]:
# Generate random 2x2 matriсes
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

# Difference matrix - matrix
result = matrix1 - matrix2

# Output
print("Matrix1:\n", matrix1)
print("Matrix2:\n", matrix2)
print("Result:\n", result)

Matrix1:
 [[1 2 6 2]
 [1 7 7 7]
 [8 8 7 2]
 [2 3 4 2]]
Matrix2:
 [[10  7  6  7]
 [ 2  1  5  4]
 [ 8  8  7  5]
 [ 5  9  4  3]]
Result:
 [[-9 -5  0 -5]
 [-1  6  2  3]
 [ 0  0  0 -3]
 [-3 -6  0 -1]]



Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [91]:
# Generate a random 3x3 matrix with values in the range [0, 1)
matrix = np.random.rand(3, 3)

# Compute the sum of each row
sum_of_rows = np.sum(matrix, axis=1)

# Output the matrix and the sum of rows
print("Matrix:\n", matrix)
print("Sum of each row:", sum_of_rows)

# One could also just multiply it by (1,1,1)

Matrix:
 [[0.62157568 0.10062823 0.8144922 ]
 [0.74515813 0.57953868 0.38813942]
 [0.6242079  0.59259691 0.68447621]]
Sum of each row: [1.53669611 1.71283624 1.90128102]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [101]:
# Generate a random 3x4 matrix with integer values 
matrix = np.random.randint(1, 6, size=(3, 4))

# Compute the square of each element in the matrix
squared_matrix = np.square(matrix)

# Output the original matrix and its squared version
print("Original Matrix:\n", matrix)
print("Squared Matrix:\n", squared_matrix)

Original Matrix:
 [[1 1 5 4]
 [5 2 3 4]
 [5 2 3 2]]
Squared Matrix:
 [[ 1  1 25 16]
 [25  4  9 16]
 [25  4  9  4]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [103]:
# Generate a random vector with integer values in the range 1 to 50
vector = np.random.randint(1, 51, size=4)

# Compute the square root of each element in the matrix
sqrt_vector = np.sqrt(vector)

# Output the original matrix and the square root matrix
print("Original Vector:\n", vector)
print("Square Root Vector:\n", sqrt_vector)

Original Vector:
 [13 35 24 42]
Square Root Vector:
 [3.60555128 5.91607978 4.89897949 6.4807407 ]
